import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const PUBS = [
    { title: "Effects of different sorting table heights on low back and shoulders biomechanical loads during dungeness crab sorting",
        meta: "[Applied Ergonomics 128, 104537]",
        authors: "Salehi, M., Choi, S., Kia, K., Chan, A., Kincl, L., Kim, J.",
        tags: ["Sorting", "Low back", "Shoulder", "Crab industry"],
        href: "https://doi.org/10.1016/j.apergo.2025.104537" },
    { title: "How to walk to reduce footstep noise in multi-story residential buildings",
        meta: "[Ergonomics 68(1), 112-119]",
        authors: "Yoon, W., Kwon, Y., Yoon, J., Choi, S., Shin, G.",
        tags: ["Walking", "Noise", "Residential buildings"],
        href: "https://doi.org/10.1080/00140139.2023.2300954" },
    { title: "Effect of medial foot loading self-practice on lower limb kinematics in young individuals with asymptomatic varus knee alignment",
        meta: "[The Knee 30, 305-313]",
        authors: "Choi, S., Shin, G.",
        tags: ["Knee", "Lower limb", "Foot loading"],
        href: "https://doi.org/10.1016/j.knee.2021.04.018" },
    { title: "Changes in low back muscle activity and spine kinematics in response to smartphone use during walking",
        meta: "[Spine 46(7), E426-E432]",
        authors: "Choi, S., Kim, M., Kim, E., Shin, G.",
        tags: ["Smartphone", "Walking", "Low back", "Spine"],
        href: "https://doi.org/10.1097/BRS.0000000000003808" },
    { title: "Performance of ground-level signal detection when using a phone while walking",
        meta: "[Accident Analysis and Prevention 151, 105909]",
        authors: "Kim, E., Kim, H., Kwon, Y., Choi, S., Shin, G.",
        tags: ["Perception", "Walking", "Phone use", "Safety"],
        href: "https://doi.org/10.1016/j.aap.2020.105909" },
    { title: "Neck muscular load when using a smartphone in sitting, standing and while walking",
        meta: "[Human Factors 63(5), 868-879]",
        authors: "Yoon, W., Choi, S., Han, H., Shin, G.",
        tags: ["Neck", "Smartphone", "Posture", "Walking"],
        href: "https://doi.org/10.1177/0018720820904237" },
    { title: "Effects of the center of mass of a stick vacuum cleaner on the muscle activities of the upper extremity during floor vacuuming",
        meta: "[Applied Ergonomics 70, 1-5]",
        authors: "Choi, S., Shin, G.",
        tags: ["Ergonomics", "Vacuuming", "Upper extremity", "Shoulder"],
        href: "https://doi.org/10.1016/j.apergo.2018.02.001" },
];
export default function Publications() {
    return (_jsxs("div", { className: "page publications-page", children: [_jsxs("section", { className: "hero hero--page", children: [_jsx("video", { className: "hero-video", src: "/video2.mp4", autoPlay: true, muted: true, loop: true, playsInline: true, preload: "auto" }), _jsx("div", { className: "hero-dim" }), " ", _jsx("div", { className: "hero-inner", children: _jsx("div", { className: "hero-copy", children: _jsx("h1", { className: "hero-title glow", children: "Publications" }) }) })] }), _jsx("main", { className: "container pub-container", children: PUBS.map((p, i) => (_jsxs("article", { className: "pub-item", children: [_jsx("a", { className: "pub-link", href: p.href || "#", children: p.title }), _jsxs("div", { className: "pub-meta", children: [p.meta, " ", p.authors] }), p.tags?.length ? (_jsx("div", { className: "pub-tags", children: p.tags.map(t => _jsx("span", { className: "pub-tag", children: t }, t)) })) : null] }, i))) })] }));
}
